baseURL = "https://genshin-feed.com/"
languageCode = "en"
title = "Genshin Feed"
disableKinds = ["categories", "tags", "RSS", "sitemap"]

[params.seo]
homeAppendTitle = "Genshin Impact RSS feeds from official Genshin Impact news!"
description = "Do you want Genshin Impact RSS feeds? Genshin Feed builds every hour RSS and Atom feeds of official Genshin Impact news and announcements!"

[params.analytics]
umamiEnable = true
