name: Generate feeds and the website

on:
  schedule:
    - cron: "0 * * * *"
  push:
  workflow_dispatch:
    inputs:
      push:
        description: "Force push"
        required: false
        default: ""

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0

      - name: Install Python dependencies with Poetry
        run: poetry install --no-dev

      - name: Run the feed generation script
        run: poetry run python generate_feed.py

      - name: Use the magic command for preparing the Hugo build
        run: ./bin/prepare-hugo-build.sh

      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.87.0"
          extended: true

      - name: Build Hugo website
        working-directory: site/
        run: hugo -v --debug

      - name: Install sshpass
        run: sudo apt install -y sshpass

      - name: Deploy the website on Gandi Simple Hosting
        if: (github.event_name == 'workflow_dispatch' && github.event.inputs.push != '') || (github.event_name == 'schedule' && github.ref == 'refs/heads/master')
        working-directory: site/
        env:
          GANDI_SHS_USER: ${{ secrets.GANDI_SHS_USER }}
          GANDI_SHS_HOST: ${{ secrets.GANDI_SHS_HOST }}
          SSHPASS: ${{ secrets.SSHPASS }}
        run: sshpass -e sftp -o StrictHostKeyChecking=no -r $GANDI_SHS_USER@$GANDI_SHS_HOST:vhosts/genshin-feed.com/htdocs <<< "put public/*"
